server.error.whitelabel.enabled=false
server.port=${ZDIPLOMA_SERVER_PORT}
server.ssl.enabled=${ZDIPLOMA_SSL_ENABLED}
server.ssl.key-store-type=PKCS12
server.ssl.key-store=${ZDIPLOMA_SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${ZDIPLOMA_SSL_KEYSTORE_PASSWORD}
server.ssl.key-alias=${ZDIPLOMA_SSL_KEYSTORE_ALIAS}

spring.application.name=ZDIPLOMA
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=11GB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=${ZDIPLOMA_MULTIPART_LOCATION}

# Connection timeout prevention when streaming large files
# 1 hour
server.tomcat.connection-timeout=3600000
# no async timeout
spring.mvc.async.request-timeout=0
server.tomcat.max-swallow-size=-1

# Spring Boot can serve static files from outside of the classpath
# This property can accept multiple comma-separated resource locations: classpath:/files/,classpath:/static-files
spring.web.resources.static-locations=${ZDIPLOMA_RESOURCES_STATIC_LOCATIONS}
spring.mvc.static-path-pattern=/**
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.web.resources.add-mappings=true

# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.SQL=DEBUG

# Database Properties
# postgresql://username:password@host:port/dbname
spring.datasource.url=${ZDIPLOMA_DB_URL}
spring.datasource.username=${ZDIPLOMA_DB_USERNAME}
spring.datasource.password=${ZDIPLOMA_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update



# Server Config
# Storage
#   zdiploma-server-config.available_storage_per_account_gb=50
zdiploma-server-config.file_storage_location=${ZDIPLOMA_FILE_STORAGE_LOCATION}
zdiploma-server-config.client_location=${ZDIPLOMA_CLIENT_LOCATION}
# HTTP 
# zdiploma-server-config.domain=${ZDIPLOMA_DOMAIN}
# Security
zdiploma-server-config.jwt_secret=${ZDIPLOMA_JWT_SECRET}
# Logging
logging.file.name=${ZDIPLOMA_SERVER_LOG}
logging.level.root=${ZDIPLOMA_LOGGING_LEVEL}